
name: CI

on:
  pull_request:
    branches: ["develop", "master"]
  push:
    tags: ["*"]
    branches: ["develop"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: --timeout=10m
          version: v1.50.1
